### ISSUE TITLE
关于新系统迁移，重新读取权限入库的错误提示

### ISSUE THREAD

**Issue by huanBird** [imzhi/jf-admin#9]
这是打印出来的log日志。
发现控制器和方法都可以识别出来。但是走到下面就报错。
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ProfileController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ProfileController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\ManageUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "\\Imzhi\\JFAdmin\\Controllers\\SettingController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\HomeController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerGroupController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerGroupController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerGroupController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BannerGroupController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\linesController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\linesController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\linesController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\linesController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\linesController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BadgeController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BadgeController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BadgeController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\BadgeController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\UserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\UserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\UserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\UserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ShopUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ShopUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ShopUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ShopUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ShopUserController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewCategoryController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewCategoryController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewCategoryController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewCategoryController"=>  
[2019-12-24 11:53:10] local.DEBUG: "App\\JFAdmin\\Controllers\\ViewCategoryController"=>  
[2019-12-24 11:53:10] local.ERROR: Undefined index: middleware {"exception":"[object] (ErrorException(code: 0): Undefined index: middleware at /var/www/buguphp/vendor/imzhi/jf-admin/src/Repositories/ManageUserRepository.php:258)
[stacktrace]
#0 /var/www/buguphp/vendor/imzhi/jf-admin/src/Repositories/ManageUserRepository.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/buguph...', 258, Array)
#1 /var/www/buguphp/vendor/imzhi/jf-admin/src/Controllers/ManageUserController.php(345): Imzhi\\JFAdmin\\Repositories\\ManageUserRepository->permissionsDetect()
#2 [internal function]: Imzhi\\JFAdmin\\Controllers\\ManageUserController->permissionsDetect()
#3 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('permissionsDete...', Array)
#5 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Imzhi\\JFAdmin\\Controllers\\ManageUserController), 'permissionsDete...')
#6 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#8 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/buguphp/vendor/imzhi/jf-admin/src/Middleware/Permission.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Imzhi\\JFAdmin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/buguphp/vendor/imzhi/jf-admin/src/Middleware/Auth.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Imzhi\\JFAdmin\\Middleware\\Auth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/buguphp/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /var/www/buguphp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 /var/www/buguphp/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 {main}
"}

**Comment by imzhi** [comment]
你好，根据报错的 258 行代码：
![image](https://user-images.githubusercontent.com/2304019/71403472-d333d600-266a-11ea-82ad-a4d328158b8d.png)
应该是你的 ``app/JFAdmin/routes.php`` 文件中有某个路由没有分配上中间件，导致 ``Undefined index: middleware`` 这个报错，你可以检查下

**Comment by huanBird** [comment]
我看你的之前的生成的Home控制器，只需要引入 use Imzhi\JFAdmin\Annotations\PermissionAnnotation;就可以自动设别注释和控制器方法。你说的这个中间件是指哪一个中间件？

**Comment by imzhi** [comment]
昨天回复的不严谨，应该是所有的路由文件里存在某个路由 没有分配任何中间件的情况，我这边代码获取对这样的路由处理不严谨导致了报错。
我修复了 258 行代码，你在项目里更新下 imzhi/jf-admin 扩展包，再试试还报错么：
```
composer update imzhi/jf-admin
```

**Comment by huanBird** [comment]
现在已经好啦。以后有问题，再次联系

**Comment by imzhi** [comment]
好的
